### ISSUE TITLE
heart beat and hrv evaluate

### ISSUE THREAD

**Issue by wanghaisheng** [fwolling/PPGraw#1]
does you know any tool or work about hr hrv evaluate from ppg sginal

**Comment by fwolling** [comment]
Hi @wanghaisheng ,
there are diverse tools one can use for heart rate and variability analysis. In one of my more recent papers, I analyzed and evaluated two popular algorithms: https://doi.org/10.1109/EMBC46164.2021.9630955
One of them is the HeartPy library for Python: https://github.com/paulvangentcom/heartrate_analysis_python
However, their performance largely depends on the quality of the input signal, the applied pre-processing/filtering, and the amount of distortion/artifacts due to motion.
Best regards,
Florian

**Comment by wanghaisheng** [comment]
I do get this is a complicated task. and I want to know do you have update of your ppgraw work
for my  knowledge   same ppg sensor combined to diff brand device can give us diff  quality signal, and your work is important If  I want to choose from various vendors provide device like smart watch

**Comment by fwolling** [comment]
Dear @wanghaisheng,
I agree with you and I have the feeling that the issue has not yet really reached the broad community. There are many, many parameters that change and affect the signal and its quality. From my side, there is no news yet, but I will attempt to raise some funding for research on it.
Of course, you can support my work by referring to my papers. 😉
I wish you a happy and successful new year 2024!
Florian

**Comment by wanghaisheng** [comment]
thanks  as u know  china got the most of manufautures like smart watch and bands ,it really no one talking about this @fwolling
